#!/bin/bash

#SBATCH --job-name=template
#SBATCH --ntasks-per-node=1
#SBATCH --mem=10G
#SBATCH --time=00:15:00

# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana University
# 
# This is the main file run by the brainlife.io orchestration system
#
# Author: Franco Pestilli

# make output directory
mkdir -p out_dir
mkdir -p out_figs

# run the actual python code
singularity exec docker://brainlife/mne:1.0.2 python3 main.py


# Store montage.png figure
cat << EOF > product.json
{
    "brainlife": [
       { 
           "type": "image/png", 
	       "name": "Montage",
           "base64": "$(base64 -w 0 out_figs/montage.png)"
       }
]
}
EOF